name: bookmark
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  http: ^1.1.0
  html: ^0.15.4
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  cached_network_image: ^3.3.0
  youtube_explode_dart: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0